const AUTH_STATE_RESET = 0x00;
const AUTH_STATE_UPDATE = 0x01;

const AUTH_REQUEST_SENT = 0x02;
const AUTH_REQUEST_SUCCEED = 0x03;
const AUTH_REQUEST_FAILED = 0x04;

export default {
  AUTH_STATE_RESET,
  AUTH_STATE_UPDATE,

  AUTH_REQUEST_SENT,
  AUTH_REQUEST_SUCCEED,
  AUTH_REQUEST_FAILED,
};
